export const TOUCH_MENU = 'TOUCH_MENU'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const FETCHING_DATA_START = 'FETCHING_DATA_START'
export const FETCHING_DATA_STOP = 'FETCHING_DATA_STOP'
export const SUB_LEAVE_SET_START_TIME = 'SUB_LEAVE_SET_START_TIME'
export const SUB_LEAVE_SET_END_TIME = 'SUB_LEAVE_SET_END_TIME'



